<div class="owl-carousel owl-theme">
	<div class="item">
	    <img src="https://source.unsplash.com/random/200x200?sig=1" />
	</div>
	<div class="item">
	    <img src="https://source.unsplash.com/random/200x200?sig=3" />
	</div>
	<div class="item">
	    <img src="https://source.unsplash.com/random/200x200?sig=2" />
	</div>
	<div class="item">
	    <img src="https://source.unsplash.com/random/200x200?sig=4" />
	</div>
	<div class="item">
	    <img src="https://source.unsplash.com/random/200x200?sig=5" />
	</div>
	<div class="item">
	    <img src="https://source.unsplash.com/random/200x200?sig=6" />
	</div>
</div>
